import Foundation

/// [4.1.1.](https://tools.ietf.org/html/rfc6749#section-4.1.1) Authorization Request
///
/// The client constructs the request URI by adding the following
/// parameters to the query component of the authorization endpoint URI
/// using the "application/x-www-form-urlencoded" format, per Appendix B.
public struct AuthRequest: Codable {
	public enum CodingKeys: String, CodingKey {
		case clientID = "client_id"
		case responseType = "response_type"
		case redirectURL = "redirect_uri"
		case state
		case scope
	}

	/// Available response types.
	public enum ResponseType: String, Codable { case code }

	/// REQUIRED.  Value MUST be set to "code".
	public var responseType: ResponseType

	/// REQUIRED.  The client identifier as described in Section 2.2.
	public var clientID: String

	/// OPTIONAL.  As described in Section 3.1.2.
	public var redirectURL: URL?

	/// OPTIONAL.  The scope of the access request as described by Section 3.3.
	public var scope: String?

	/// RECOMMENDED.  An opaque value used by the client to maintain
	/// state between the request and callback.
	///
	/// The authorization server includes this value when redirecting the user-agent back
	/// to the client.  The parameter SHOULD be used for preventing
	/// cross-site request forgery as described in Section 10.12.
	public var state: String?

	/// Creates a new `AuthRequest`.
	///
	/// - Parameter responseType: The type of the response.
	/// - Parameter clientID: The client identifier.
	/// - Parameter redirectURL: The URL that the response should be redirected to.
	/// - Parameter state: A state property that the response should include.
	/// - Parameter scope: The scope of the access request.
	public init(
		responseType: ResponseType = .code,
		clientID: String,
		redirectURL: URL,
		state: String?,
		scope: String?
	) {
		self.responseType = responseType
		self.clientID = clientID
		self.redirectURL = redirectURL
		self.state = state
		self.scope = scope
	}

	/// Creates a new `AuthRequest` without a redirect URL.
	///
	/// - Parameter responseType: The type of the response.
	/// - Parameter clientID: The client identifier.
	/// - Parameter state: A state property that the response should include.
	/// - Parameter scope: The scope of the access request.
	public init(
		responseType: ResponseType = .code,
		clientID: String,
		state: String?,
		scope: String?
	) {
		self.responseType = responseType
		self.clientID = clientID
		self.redirectURL = nil
		self.state = state
		self.scope = scope
	}
}

/// [4.1.2.](https://tools.ietf.org/html/rfc6749#section-4.1.2) Authorization Response
///
/// If the resource owner grants the access request, the authorizatio
/// server issues an authorization code and delivers it to the client b
/// adding the following parameters to the query component of th
/// redirection URI using the "application/x-www-form-urlencoded" format
/// per Appendix B.
public struct AuthResponse: Codable {
	public enum CodingKeys: String, CodingKey {
		case code, state
	}

	/// REQUIRED.  The authorization code generated by the
	/// authorization server.  The authorization code MUST expire
	/// shortly after it is issued to mitigate the risk of leaks.
	///
	/// A maximum authorization code lifetime of 10 minutes is
	/// RECOMMENDED.  The client MUST NOT use the authorization code
	/// more than once.  If an authorization code is used more than
	/// once, the authorization server MUST deny the request and SHOULD
	/// revoke (when possible) all tokens previously issued based on
	/// that authorization code.  The authorization code is bound to
	/// the client identifier and redirection URI.
	public var code: String

	/// REQUIRED if the "state" parameter was present in the client
	/// authorization request.  The exact value received from the
	/// client.
	public var state: String?

	/// Creates a new AuthResponse.
	///
	/// - Parameter code: The authorization code to use when requesting an access token.
	/// - Parameter state: The state that was included in the `AuthRequest`.
	public init(code: String, state: String?) {
		self.code = code
		self.state = state
	}
}
